import Layout from "@/components/layout/Layout";
import localFont from "next/font/local";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import ReactQueryProvider from "@/utils/providers/ReactQueryProvider";
import NextAuthProvider from "@/utils/providers/NextAuthProvider";

const PoetsenOneFont = localFont({
  src: "../../public/fonts/PoetsenOne-Regular.ttf",
});

export const metadata = {
  title: "Feedback Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={PoetsenOneFont.className}>
        <Toaster />
        <ReactQueryProvider>
          <NextAuthProvider>
            <Layout>{children}</Layout>
          </NextAuthProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
